### PR TITLE
[WBA-691] Allow exclusions per path end method

### PR DESCRIPTION
**Pull request by MihailSirbu**
Updated path exclusions to optionally match both HTTP path and method.
You can now use both:
```ruby
Wb::Service::RailsSupport::JWT.register_middleware(
    secret: ENV.fetch("API_CLIENT_JWT_SECRET", "test-secret"),
    exclude_paths: "/ping",
    optional_paths: "/games/joinable",
  )
)
```
and: 
```ruby
Wb::Service::RailsSupport::JWT.register_middleware(
    secret: ENV.fetch("API_CLIENT_JWT_SECRET", "test-secret"),
    exclude_paths: {
      "/ping" => { :only: => [:get, :put] }
    },
    optional_paths: {
      "/games/joinable" => { :only => [:get, :put] }
    }
  )
) 
```
 And if you don't want to specify method on existing paths, you can use empty hash
```ruby
optional_paths: {
  "/path1" => {},
}
```

Optional shorthand syntax:
1. `'/path' => :get` is considered as `'/path' => { :only => [:get] }`
2. `'/path' => { :only => :get }` to considered as `'/path' => { :only => [:get] }`

### CODE REVIEW

**Comment by dphaener** [comment]
@MihailSirbu General question. How would this solution scale if we wanted to add multiple verbs to the exclude/optional list? Would it be better to structure it something like:
```ruby
Wb::Service::RailsSupport::JWT.register_middleware(
    secret: ENV.fetch("API_CLIENT_JWT_SECRET", "test-secret"),
    exclude_paths: {
       "/ping" => only: [:get, :index]
    },
    optional_paths: {
      "/games/joinable" => only: [:get, :index],
    }
  )
) 
```
That's 100% pseudo code, but I like the idea of using that Rails style convention for before/after hooks:

**Comment by frank-west-iii** [comment]
I think @dphaener's suggestion is a more flexible implementation.

**Comment by swerling** [comment]
@MihailSirbu I'm agnostic on changing the format, since your array format also allows multiple versions.

Before you merge you might want to test it out using postman by 
* cloning your branch into <membership-service>/vendor/gems/dev/rack-jwt
* setting RACK_JWT_GEM_PATH in your memberships service env
* then playing around w/ exclude paths in config/application.rb and making sure it does the expected thing, and that logging is appropriate on 401s

**Comment by MihailSirbu** [comment]
@dphaener Thanks for the suggestion. My implementation allowed multiples as ` "/games/joinable",  'get|put'`, but your's does look a lot cleaner since less regex is used. I'll try it tomorrow.

**Comment by MihailSirbu** [comment]
@swerling @dphaener I just updated to th enew syntax (please see PR's description) and tested it by making call from Postman.

That was quite useful, since I immediately discovered that we need to be more lenient or argument errors. I've set it to allow `nil, [], {}` since all three indicate that you don't want to specify any method checking. 
```ruby
    Wb::Service::RailsSupport::JWT.register_middleware(
      secret: ENV.fetch("API_CLIENT_JWT_SECRET", "test-secret"),
      exclude_paths: ["/ping"],
      optional_paths: [
        "/games/joinable" => nil,
        '/games/\d+\/?\z' => [], # Must be single quoted when including a regex.
        '/games/\d+\/membership_offer' => {}
      ]
    )
```

**Comment by dphaener** [comment]
@MihailSirbu Can you also pass an array of http verbs? I think accepting an empty array as an empty value might be misleading. I'll let the team at large weigh on this, but my preference would be to only allow an empty object.

**Comment by MihailSirbu** [comment]
@dphaener sure, I can make `=> [:get]` be translated to `=> {:only => [:get]}`. Is this a common rails practice?

As for `nil` and `[]`, the reason I added them is that if argument error is thrown, then the rails application does not start at all. I see myself or others slipping in a `nil` instead of `{}` and crashing everything

**Comment by dphaener** [comment]
@MihailSirbu What I'm saying here is I'd rather have a single API, not a multitude of ways to describe which verbs are excluded. If someone slips and adds the wrong argument yes the app will fail to run entirely, but I think that's fine. If we're testing in development we'll find out real quick. I would also assume that any integration specs would also quickly fail in that case.

**Comment by MihailSirbu** [comment]
@dphaener How about also translating `{:only => :get}` to `{:only => [:get]}`. Seems logical to have either symbol/string or array of symbols/string

**Comment by dphaener** [comment]
@MihailSirbu I'm ok with that if everyone else is.

**Comment by MihailSirbu** [comment]
@dphaener Added three last changes:
1. Don't allow `'/path' => []` and `'/path' => nil`
2. Allow shorthand '/path' => :get` to considered as `'/path' => { :only => [:get] }`  (Note: you can either use string or symbol here for http vert )
3. Allow shorthand '/path' => { :only => :get }` to considered as `'/path' => { :only => [:get] }`  (Note: you can either use string or symbol here for http verb )

**Pull request merged**
